# Generated by Django 3.1.6 on 2021-02-03 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mob', models.CharField(max_length=12)),
                ('add1', models.CharField(max_length=30)),
                ('add2', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('rating', models.IntegerField(default=4)),
                ('cost_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('image2', models.ImageField(null=True, upload_to='')),
                ('image3', models.ImageField(null=True, upload_to='')),
                ('image4', models.ImageField(null=True, upload_to='')),
                ('image5', models.ImageField(null=True, upload_to='')),
                ('qty_available', models.IntegerField(default=1)),
                ('unit', models.CharField(blank=True, max_length=10)),
                ('categoriy', models.CharField(blank=True, max_length=20)),
                ('sub_category', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('brief_description', models.CharField(blank=True, max_length=30)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.product'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mob', models.CharField(max_length=12)),
                ('add1', models.CharField(max_length=30)),
                ('add2', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=20)),
                ('cart', models.ManyToManyField(null=True, to='app1.Product')),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
