# Generated by Django 3.1.6 on 2021-02-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cart',
        ),
        migrations.AddField(
            model_name='client',
            name='cart',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
