# Generated by Django 3.1.6 on 2021-02-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210205_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='wishlist',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
