# Generated by Django 3.1.6 on 2021-02-04 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_client_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoriy',
            new_name='category',
        ),
    ]
